name: dhoni_coffee_machine
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  cloud_firestore: ^4.17.2
  day_night_time_picker: ^1.3.1
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  uuid: ^4.4.0
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: ReenieBeanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf
